services:
  db:
    image: mysql:8.0
    container_name: ${APP_NAME}_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3307:${DATABASE_PORT}"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - btx-network

  backend:
    build: ./backend
    container_name: ${APP_NAME}_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
    depends_on:
      - db
    networks:
      - btx-network

  frontend:
    build: ./frontend
    container_name: ${APP_NAME}_frontend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - btx-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    ports:
      - "8011:80"
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: ${DATABASE_USER}
      PMA_PASSWORD: ${DATABASE_PASSWORD}

networks:
  btx-network:
    driver: bridge
